### ISSUE TITLE
Missing part on BOM?

### ISSUE THREAD

**Issue by pronettixs** [MaslowCNC/PCBs#10]
While reviewing the PCB in Eagle i noticed 2 component with i could not find on the BOM. 
Above the H-Bridges there are 2 SMD components. Are these .1uF capasitors?

![Uploading missingParts.JPG…]()

**Comment by pronettixs** [comment]
![missingparts](https://cloud.githubusercontent.com/assets/20775375/22693357/3da987c8-ed43-11e6-89d2-42c7c3a8dc33.JPG)

**Comment by BarbourSmith** [comment]
Those are the .1uF filtering capacitors. I added the value to the description on the BOM to make it more clear. Thanks for pointing that out.

Do you think that's clear enough, or is there more we can do to make it clearer?

**Comment by pronettixs** [comment]
Thanks, this is clear enough.
