### ISSUE TITLE
Aux vias are not in a grid.

### ISSUE THREAD

**Issue by JDogHerman** [MaslowCNC/PCBs#28]
The 5v pin on Aux vias 1-5 are not inline with the ground pin. The silk screen is good but the pin is off. I can see this on the board I had printed and from the board in the store.

**Comment by BarbourSmith** [comment]
Yes! (but this is intentional 😀 )

If you stick headers in them they will be held in place by the slight offset making it easier to solder

**Comment by blurfl** [comment]
Is the explanation sufficient? Can this be closed?
