### ISSUE TITLE
J4 - Power Jack Part Number

### ISSUE THREAD

**Issue by blurfl** [MaslowCNC/PCBs#31]
Is it possible that the part used for J4, the 12V power jack changed from the device shown in the BOM?
The BOM shows a CP-002A-ND, which has a 2mm center pin. The jack on the v1.1 board has a 2.5mm center pin. The DigiKey part number for that would be CP-002B-ND.

**Comment by BarbourSmith** [comment]
Great catch @blurfl 

I checked the invoice and the part we are using is [CP-202BH-ND](https://www.digikey.com/product-detail/en/cui-inc/PJ-202BH/CP-202BH-ND/408451 )

I will update the BOM right now

**Comment by blurfl** [comment]
I see, that one has the higher (5A) current rating. From a company from Tualatin, OR., too 😄

**Comment by BarbourSmith** [comment]
No way! That's a 15 minute drive away and I had no idea. Maybe we'll drop by to say hello
