### ISSUE TITLE
LED Current too high

### ISSUE THREAD

**Issue by dmouw25** [MaslowCNC/PCBs#45]
The current through the 12VPOWER LED is too high and power dissipation of R2 is very high.   LED is rated for 25mA maximum and LED is currently being driven at 29mA ((12V-2.2V)/330 ohm).   Resistor R2 is currently dissipating 290mW typical.  Increasing resistor R2 to 1000 ohm would allow a normal 0805 resistor to be used instead of thick metal film resistor selected for a small cost savings and will reduced board power dissipation by 190mW.   This will set LED to a  nominal current of 10mA and worst case current at ~12mA.   This will match the 5V LED current,   If maximum brightness is desired, R2 can be set to 510 ohm, which should guarentee that LED current stays below 25mA (assuming 12V supply stays under 13V)

**Comment by blurfl** [comment]
A good catch! Great that you're checking deeply into the circuitry. Do you want to do a PR on this, or shall I?

**Comment by dmouw25** [comment]
Not sure how to do a PR, so could you do it?

**Comment by blurfl** [comment]
I'll be glad to. To summarize, I'll change the value of R2 to 1K on the schematic and the BOM, and look up a 1K SMD thin-film resistor for the BOM, yes?

**Comment by dmouw25** [comment]
Correct.   I would personally go with 541-4162-1-ND at digikey But that is mostly because that is a company we use at work.

**Comment by blurfl** [comment]
I'm a great fan of DigiKey too. Thanks for the part number 💯

**Comment by BarbourSmith** [comment]
Excellent suggestion! Let's change the part in the BOM and change the value for that resistor in the schematic. 👍 👍 💯

**Comment by blurfl** [comment]
Ok to close this?

**Comment by BarbourSmith** [comment]
I vote to close. Well added!
