### ISSUE TITLE
[FEATURE REQUEST] KiCad version of PCB

### ISSUE THREAD

**Issue by darigovresearch** [MaslowCNC/PCBs#60]
We may get more contributions/improvements to the system if it is in an open source PCB format like KiCad as it would reduce the barrier to entry for new users. Was wondering if the maintainers or someone from the community would be interested in trying this out.

https://www.kicad.org/

**Comment by darigovresearch** [comment]
@midopple any chance you could do what you done to resolve https://github.com/drspangle/infidel-sensor/issues/24 here?

**Comment by midopple** [comment]
Hi, 
i have added the Kicad Files #61
Please check it, at my first check i see no errors

![grafik](https://user-images.githubusercontent.com/1327091/116130682-ce05f180-a6cb-11eb-982f-586c83b63d8a.png)

**Comment by darigovresearch** [comment]
Hi, @midopple thanks for being kind enough to tackle this issue. We're still learning KiCad but will raise any issues if we see any pop up so will close this as you managed to generate the files which is a great start!
